development:
  adapter: mysql
  database: geobob_interactive
  username: root
  password: atul12
  host: localhost
  encoding: utf8

test: &TEST
  adapter: mysql
  database: geobob_test
  username: root
  password:
  host: localhost
  encoding: utf8

staging:
  adapter: mysql
  database: geobob_staging
  username: geobob
  password: 
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql
  database: geobobif_production
  username: bob
  password: djdu248!#$%dfgj^
  host: localhost
  encoding: utf8
  #socket: /var/lib/mysql/mysql.sock

cucumber:
  <<: *TEST
